version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:23"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - npm
    groups:
      npm-production:
        dependency-type: production
      npm-development:
        dependency-type: development

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
      day: monday
      time: "09:43"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    labels:
      - dependencies
      - github-actions
